### ISSUE TITLE
TypeError: Cannot read property 'unprefixed' of undefined

### ISSUE THREAD

**Issue by brachycera** [hudochenkov/stylelint-order#127]
The following two error messages occur in Sublime Text and VS-Code. 

- Stylelint-order@4.1.0
- postcss@8.1.1 

Possible related to #126.

## Sublime Error
```
SublimeLinter: WARNING: stylelint output:
postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
TypeError: Cannot read property 'unprefixed' of undefined
    at /Users/superfly/test.css:15:1
    at getNodeData (/usr/local/lib/node_modules/stylelint-order/rules/properties-order/getNodeData.js:7:39)
    at /usr/local/lib/node_modules/stylelint-order/rules/properties-order/checkNodeForOrder.js:99:19
    at Array.map (<anonymous>)
    at getAllPropertiesData (/usr/local/lib/node_modules/stylelint-order/rules/properties-order/checkNodeForOrder.js:99:5)
    at checkNodeForOrder (/usr/local/lib/node_modules/stylelint-order/rules/properties-order/checkNodeForOrder.js:65:2)
    at processRulesAndAtrules (/usr/local/lib/node_modules/stylelint-order/rules/properties-order/index.js:54:5)
    at /usr/local/lib/node_modules/stylelint/node_modules/postcss/lib/container.js:139:18
    at Root.each (/usr/local/lib/node_modules/stylelint/node_modules/postcss/lib/container.js:105:16)
    at Root.walk (/usr/local/lib/node_modules/stylelint/node_modules/postcss/lib/container.js:135:17)
    at ruleBody (/usr/local/lib/node_modules/stylelint-order/rules/properties-order/index.js:43:8)
```

## VS-Code Error
```
TypeError: Cannot read property 'unprefixed' of undefined     
    at /Users/superfly/test.css:15:1     
    at getNodeData (/usr/local/lib/node_modules/stylelint-order/rules/properties-order/getNodeData.js:7:39)     
    at /usr/local/lib/node_modules/stylelint-order/rules/properties-order/checkNodeForOrder.js:99:19     
    at Array.map (<anonymous>)     
    at getAllPropertiesData (/usr/local/lib/node_modules/stylelint-order/rules/properties-order/checkNodeForOrder.js:99:5)     
    at checkNodeForOrder (/usr/local/lib/node_modules/stylelint-order/rules/properties-order/checkNodeForOrder.js:65:2)     
    at processRulesAndAtrules (/usr/local/lib/node_modules/stylelint-order/rules/properties-order/index.js:54:5)     
    at /Users/superfly/.vscode/extensions/shinnn.stylelint-0.51.0/node_modules/postcss/lib/container.js:135:18     
    at Root.each (/Users/superfly/.vscode/extensions/shinnn.stylelint-0.51.0/node_modules/postcss/lib/container.js:101:16)     
    at Root.walk (/Users/superfly/.vscode/extensions/shinnn.stylelint-0.51.0/node_modules/postcss/lib/container.js:131:17)     
    at ruleBody (/usr/local/lib/node_modules/stylelint-order/rules/properties-order/index.js:43:8)
```

**Comment by hudochenkov** [comment]
stylelint-order is not running on PostCSS 8 yet.

**Comment by brachycera** [comment]
Thanks for your response Aleks. I just thought I put it here so others can see that stylelint-order isn't postCSS8 ready yet ;-)

**Comment by hudochenkov** [comment]
How do you run it? Because stylelint didn't migrate to PostCSS 8 also.

**Comment by brachycera** [comment]
I run stylelint@13.7.2 and postcss@8.1.1 globally and use them via https://github.com/stylelint/vscode-stylelint and https://github.com/SublimeLinter/SublimeLinter-stylelint. There is a config file under ~/.stylelint where I have defined some rules and the stylelint-order plugin.

**Comment by hudochenkov** [comment]
I'll close this one in favor of https://github.com/hudochenkov/stylelint-order/issues/126
