### ISSUE TITLE
Getting error after update to 6.0.2

### ISSUE THREAD

**Issue by morewings** [hudochenkov/stylelint-order#172]
After update, I started to get the following error after running `stylelint 'src/**/*.{ts,tsx}' --fix`
Version `5.0.0` works ok

```
TypeError: Cannot read properties of undefined (reading 'includes')
    at /Users/dima/Dev/olx-ui-library/src/core/Avatar/Avatar.stories.tsx:24:24
    at isAllowedToProcess (/Users/dima/Dev/olx-ui-library/node_modules/.pnpm/postcss-sorting@8.0.1_postcss@8.4.17/node_modules/postcss-sorting/lib/isAllowedToProcess.js:13:22)
    at sortNodeProperties (/Users/dima/Dev/olx-ui-library/node_modules/.pnpm/postcss-sorting@8.0.1_postcss@8.4.17/node_modules/postcss-sorting/lib/properties-order/sortNodeProperties.js:12:7)
    at processRulesAndAtrules (/Users/dima/Dev/olx-ui-library/node_modules/.pnpm/stylelint-order@6.0.1_stylelint@15.2.0/node_modules/stylelint-order/rules/properties-alphabetical-order/index.js:37:6)
    at /Users/dima/Dev/olx-ui-library/node_modules/.pnpm/postcss@8.4.17/node_modules/postcss/lib/container.js:55:18
    at Root.each (/Users/dima/Dev/olx-ui-library/node_modules/.pnpm/postcss@8.4.17/node_modules/postcss/lib/container.js:41:16)
    at Root.walk (/Users/dima/Dev/olx-ui-library/node_modules/.pnpm/postcss@8.4.17/node_modules/postcss/lib/container.js:52:17)
    at ruleBody (/Users/dima/Dev/olx-ui-library/node_modules/.pnpm/stylelint-order@6.0.1_stylelint@15.2.0/node_modules/stylelint-order/rules/properties-alphabetical-order/index.js:25:8)
    at /Users/dima/Dev/olx-ui-library/node_modules/.pnpm/stylelint@15.2.0/node_modules/stylelint/lib/lintPostcssResult.js:114:8
    at Array.map (<anonymous>)
    at lintPostcssResult (/Users/dima/Dev/olx-ui-library/node_modules/.pnpm/stylelint@15.2.0/node_modules/stylelint/lib/lintPostcssResult.js:105:18)
    at lintSource (/Users/dima/Dev/olx-ui-library/node_modules/.pnpm/stylelint@15.2.0/node_modules/stylelint/lib/lintSource.js:110:8)
    at async /Users/dima/Dev/olx-ui-library/node_modules/.pnpm/stylelint@15.2.0/node_modules/stylelint/lib/standalone.js:203:27
    at async Promise.all (index 77)
    at async standalone (/Users/dima/Dev/olx-ui-library/node_modules/.pnpm/stylelint@15.2.0/node_modules/stylelint/lib/standalone.js:246:22)
```

`package.json`
```
"@stylelint/postcss-css-in-js": "0.38.0",
"postcss": "8.4.17",
"postcss-syntax": "0.36.2",
"stylelint": "15.2.0",
"stylelint-config-standard": "30.0.1",
"stylelint-config-styled-components": "0.1.1",
"stylelint-order": "6.0.2",
```

`stylelint.config.cjs`
```
module.exports = {
    extends: [
        'stylelint-config-standard',
        'stylelint-config-styled-components'
    ],
    customSyntax: '@stylelint/postcss-css-in-js',
    plugins: ['stylelint-order'],
    rules: {
        /**
         * Enforce alphabetical order for properties and custom properties before standard
         * @see https://github.com/hudochenkov/stylelint-order
         */
        'order/order': ['custom-properties', 'declarations'],
        'order/properties-alphabetical-order': true,
        /** Disable rules which conflict with Prettier */
        'function-no-unknown': null,
        'value-keyword-case': null,
        'function-name-case': null,
        'property-no-unknown': [true, { ignoreProperties: ['should-forward-prop'] }],
        'custom-property-pattern': null,
        'selector-class-pattern': null,
        'annotation-no-unknown': null,
        'custom-property-empty-line-before': null
    }
};

```

**Comment by hudochenkov** [comment]
Try to remove deprecated `@stylelint/postcss-css-in-js` and `postcss-syntax`. Use [`postcss-styled-syntax`](https://github.com/hudochenkov/postcss-styled-syntax) instead.

**Comment by morewings** [comment]
@hudochenkov thanks for the hint. What prevents you from contributing to @stylelint/postcss-css-in-js package? In my opinion, there are too many postcss-syntax libraries at the moment.

**Comment by hudochenkov** [comment]
@morewings that package is deprecated. It was doing too much. It was a great solution at the time, but technical implementation, unfortunately, made it impossible to make it work with PostCSS 8.

From stylelint [migration guide](https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-15.md):

> We've also deprecated the [postcss-css-in-js](https://www.npmjs.com/package/@stylelint/postcss-css-in-js) custom syntax. It was not possible to maintain a monolithic custom syntax that attempted to support every CSS-in-JS library and syntax, as there are so many of them and each with variations in syntax.

**Comment by morewings** [comment]
Thanks for the info. As a user I can give feedback, I wish one day it will be like @rollup or @eslint. So I can pick all the tools from one vendor.

**Comment by morewings** [comment]
Your proposition worked, so I'm closing the issue. Thanks for your work again, @hudochenkov
