### ISSUE TITLE
Crash: TypeError: Cannot read property 'orderData' of undefined

### ISSUE THREAD

**Issue by subzey** [hudochenkov/stylelint-order#19]
I am using **stylelint 7.9.0** with **stylelint-order 0.4.0** and it crashes on a specific LESS input.

The callstack:
```
TypeError: Cannot read property 'orderData' of undefined
    at checkEmptyLineBefore (/home/akhlynovskiy/code/tradingview/node_modules/stylelint-order/rules/properties-order/index.js:236:50)
    at processEveryNode (/home/akhlynovskiy/code/tradingview/node_modules/stylelint-order/rules/properties-order/index.js:147:5)
    at Rule.each (/home/akhlynovskiy/code/tradingview/node_modules/postcss/lib/container.js:114:22)
    at checkNode (/home/akhlynovskiy/code/tradingview/node_modules/stylelint-order/rules/properties-order/index.js:66:9)
    at processRulesAndAtrules (/home/akhlynovskiy/code/tradingview/node_modules/stylelint-order/rules/properties-order/index.js:52:5)
    at /home/akhlynovskiy/code/tradingview/node_modules/postcss/lib/container.js:148:26
    at Root.each (/home/akhlynovskiy/code/tradingview/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/home/akhlynovskiy/code/tradingview/node_modules/postcss/lib/container.js:147:21)
    at /home/akhlynovskiy/code/tradingview/node_modules/stylelint-order/rules/properties-order/index.js:50:8
    at Promise.resolve.then (/home/akhlynovskiy/code/tradingview/node_modules/stylelint/lib/lintSource.js:122:52)
```

Here's the setup to reproduce the crash.

`.stylelintrc.js`:
```js
module.exports.plugins = ['stylelint-order'];
module.exports.rules = {
	'order/properties-order': [
		[
			'content',
			'display',
			'position',
			'float',
		],
		{
			unspecified: 'bottom',
			severity: 'warning',
		}
	],
};
```

`test.less`:
```less
.selector {
	display: block;
	@less-variable: 42;
}
```
As far as I understand, the crash happens if any LESS variable declaration follows any "regular" property.

Please ping me if you need any additional information or help.

**Comment by hudochenkov** [comment]
Thank you for your report! Please, update to `0.4.1`.
