### ISSUE TITLE
Custom properties parsing broken in 0.4.2

### ISSUE THREAD

**Issue by doochik** [hudochenkov/stylelint-order#21]
This code works in 0.4.1 and broken in 0.4.2

```css
:root {
   --foo: {
      top: 0;
      color: pink;
   }
}
```

JS error
```
TypeError: Cannot read property '0' of undefined
      at Object.isStandardSyntaxProperty (utils/isStandardSyntaxProperty.js:10:14)
      at processEveryNode (rules/properties-order/index.js:118:22)
      at Rule.each (node_modules/postcss/lib/container.js:114:22)
      at checkNode (rules/properties-order/index.js:66:9)
      at processRulesAndAtrules (rules/properties-order/index.js:52:5)
      at node_modules/postcss/lib/container.js:148:26
      at Root.each (node_modules/postcss/lib/container.js:114:22)
      at Root.walk (node_modules/postcss/lib/container.js:147:21)
      at rules/properties-order/index.js:50:8
      at Promise.resolve.then (node_modules/stylelint/lib/lintSource.js:122:52)
```

**Comment by hudochenkov** [comment]
Thank you for the report and fix! Please update to `0.4.3`.
